# Generated by Django 5.2 on 2025-04-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.CharField(max_length=20)),
                ('couleur', models.CharField(max_length=30)),
                ('immatriculation', models.CharField(max_length=30)),
            ],
        ),
    ]
