# Generated by Django 5.2 on 2025-04-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='marque',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
